name: revup_provider
description: A very good app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  bloc: ^8.0.3
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.3.1
  flutter_form_field_validator: ^1.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  revup_core:
    git:
      url: https://github.com/Revup-vn/revup-core.git
      ref: main
      version: ^3.4.1-dev

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  dependency_validator: ^3.2.0
  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
