name: revup_provider
description: A very good app
version: 1.0.0-dev+11
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_settings: ^4.1.8
  auto_route: ^5.0.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  dartz: ^0.10.1
  dio: ^4.0.1
  dotted_border: ^2.0.0+2
  firebase_core: ^1.20.0
  fl_chart: ^0.55.1
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^7.5.0
  flutter_form_field_validator: ^1.0.0
  flutter_html: ^3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.3
  flutter_switch: ^0.3.2
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.0.3
  geoflutterfire2: ^2.3.12
  geolocator: ^9.0.1
  google_maps_flutter: ^2.2.0
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  introduction_screen: ^3.0.1
  json_annotation: ^4.6.0
  loader_overlay: ^2.0.10
  lottie: ^1.4.2
  map_launcher: ^2.3.0+1
  modal_bottom_sheet: ^2.1.0
  pin_code_fields: ^7.4.0
  revup_core:
    # path: ../revup-core
    git:
      url: https://github.com/Revup-vn/revup-core.git
      ref: main
      version: ^6.3.7-dev+1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  tiengviet: ^0.5.0
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^5.0.1
  bloc_test: ^9.1.0
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  dependency_validator: ^3.2.0
  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

import_sorter:
  comments: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/screens/
    - assets/common_service.json
